//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AvailableSubjects
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AvailableSubjects()
        {
            this.EnrolledSubject = new HashSet<EnrolledSubject>();
            this.Schedules = new HashSet<Schedules>();
        }
    
        public int Id { get; set; }
        public Nullable<int> SubjectId { get; set; }
        public Nullable<int> AvailableCourseId { get; set; }
        public string SubjectCode { get; set; }
        public string TeacherId { get; set; }
        public string Schedule { get; set; }
    
        public virtual AvailableCourses AvailableCourses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EnrolledSubject> EnrolledSubject { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Schedules> Schedules { get; set; }
        public virtual Subjects Subjects { get; set; }
        public virtual UserDetails UserDetails { get; set; }
    }
}
