//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Credits
    {
        public int Id { get; set; }
        public string UserId { get; set; }
        public string State { get; set; }
        public int Credit { get; set; }
        public decimal AmountPaid { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<System.DateTime> DatePaid { get; set; }
        public string PayBy { get; set; }
        public string PayId { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
