//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Grades
    {
        public int Id { get; set; }
        public Nullable<int> EnrolledSubjectId { get; set; }
        public Nullable<decimal> Prelim { get; set; }
        public Nullable<decimal> MidTerm { get; set; }
        public Nullable<decimal> FinalTerm { get; set; }
    
        public virtual EnrolledSubject EnrolledSubject { get; set; }
    }
}
