//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Messages
    {
        public int Id { get; set; }
        public string MessageFrom { get; set; }
        public string MessageTo { get; set; }
        public string Subject { get; set; }
        public string Message { get; set; }
        public byte[] Files { get; set; }
        public string FileName { get; set; }
        public string MimeType { get; set; }
        public string ExtensionName { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<bool> Status { get; set; }
        public string CreatedBy { get; set; }
    }
}
